//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBasket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cartid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> vegid { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> Flowerid { get; set; }
        public Nullable<int> pacid { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<int> quantity { get; set; }
        public byte[] image { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Fruit Fruit { get; set; }
        public virtual Flower Flower { get; set; }
        public virtual Meat Meat { get; set; }
        public virtual packedfood packedfood { get; set; }
        public virtual Vegetable Vegetable { get; set; }
        public virtual User User { get; set; }
    }
}
