//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBasket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class todayoffer
    {
        public Nullable<int> userid { get; set; }
        public int productid { get; set; }
        public string name { get; set; }
        public Nullable<int> originalcost { get; set; }
        public Nullable<int> retailprice { get; set; }
        public Nullable<int> stock { get; set; }
        public byte[] image { get; set; }
        public string offer { get; set; }
        public string category { get; set; }
    
        public virtual User User { get; set; }
    }
}
